# Generated by Django 5.0.2 on 2025-07-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_orderposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
